### ISSUE TITLE
Explanation of MicroIoU

### ISSUE THREAD

**Issue by JulienMaille** [qubvel/open-cities-challenge#2]
Congratulations for the 1st place!
May I ask what is MicroIoU doing? And drop_empty for IoU?
Thanks in advance!

**Comment by qubvel** [comment]
MicroIoU: calculate Intersection pixels and Union pixels across all dataset (not mean IoU over images)
drop_empty: calculate loss/metric only for images with instances (drop images with all "0" pixels masks)

**Comment by JulienMaille** [comment]
Thank you,
MicroIoU: I wrote something on my fork that I called partial_IoU. It returns (I, U) of a batch, so that at the end of the epoch, I can perform sum(I)/sum(U) This is quite useful when a class is missing in many images.
Looking at your code, I don't understand how you can do the same by returning a score for the current batch?!

drop_empty: if an instance is missin (U=0), then do you ignore false positive?

**Comment by qubvel** [comment]
Metric accumulate I and U by itself, and return always accumulated microIoU. So, correct microIoU would be returned for last batch of epoch and on start of each epoch metric is reset.

drop_empty: yes, ignore false positive on such case. we have enough negative pixels on images with objects and micro IoU does not penalize us too much for small noise on empty images.
